[package]
name = "slct"
version = "0.2.0"
license = "Unlicense"
authors = ["Dmitri Melnikov <github@dmit.me>"]
edition = "2018"
resolver = "2"
publish = false

[dependencies]
ahash = "0.7.4"
argh = "0.1.5"
