# Nightly features are commented out to keep formatting
# consistent regardless of which toolchain is used.

edition = "2021"
# version = "Two"
# unstable_features = true

# condense_wildcard_suffixes = true
# enum_discrim_align_threshold = 20
# fn_single_line = true
# format_code_in_doc_comments = true
# format_macro_bodies = true
# format_macro_matchers = true
# group_imports = "StdExternalCrate"
max_width = 100
# merge_imports = true
newline_style = "Unix"
# overflow_delimited_expr = true
# reorder_impl_items = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
# wrap_comments = true
